#:schema https://mise.jdx.dev/schema/mise.json

[settings.skills]
dir = ".agents/skills"
auto_sync = true
prune = true

[settings.packslip]
exec = true

[task_config]
includes = ["tasks.toml"]

[task_config.cache]
enabled = true

[tools]
hk = "latest"
pkl = "latest"
shellharden = "latest"
shellcheck = "0.11.0"
"go:mvdan.cc/sh/v3/cmd/shfmt" = "latest"
