#! /usr/bin/env bash
#:schema https://mise.jdx.dev/schema/mise-task.json

["render:tasks"]
description = "Generate tasks documentation"
env = { CLICOLOR_FORCE = "0" }
run = [
  "mise generate task-docs --output tasks.md --style detailed",
]
sources = ["mise"]
outputs = ["tasks.md"]

[pre-commit]
run = "hk run pre-commit --no-fail-fast"

[check]
run = "hk check --all --no-fail-fast --stats"

[fix]
run = "hk fix --all --no-fail-fast --stats"
