#! /usr/bin/env bash
#:schema https://mise.jdx.dev/schema/mise-task.json

["render:tasks"]
description = "Generate tasks documentation"
env = { CLICOLOR_FORCE = "0" }
run = [
  "mise generate task-docs --output tasks.md --style detailed --inject ",
]
sources = ["mise"]
outputs = ["tasks.md"]

[Check-staged]
run = "hk check --staged --no-fail-fast"

[Check-all]
run = "hk check --all --no-fail-fast"

[Fix-all]
run = "hk fix --all --no-fail-fast "

[Chezmoi-edit-config]
run = "chezmoi edit-config"
