[completions.mise]
  bash = [
    { name = "copilot", cmd = "completion bash" },
    { name = "hk", cmd = "completion bash" },
    { name = "tombi", cmd = "completion bash" },
    { name = "delta", cmd = "--generate-completion bash" },
    { name = "ryl", cmd = "--generate-completions bash" }
  ]
  powershell = []
