[completions]
  mise = [
    { name = "copilot", cmd = "completion" },
    { name = "hk", cmd = "completion" },
    { name = "tombi", cmd = "completion" },
    { name = "delta", cmd = "--generate-completion" },
    { name = "ryl", cmd = "--generate-completions" },
    { name = "betterleaks", cmd = "completion" },
  ]
