[extensions.vscode]
all = ["hashicorp.terraform", "golang.go", "openai.chatgpt", "tombi-toml.tombi", "hverlin.mise-vscode", "timonwong.shellcheck", "ms-azuretools.vscode-containers", "mads-hartmann.bash-ide-vscode", "timonwong.shellcheck", "gruntfuggly.todo-tree", "foxundermoon.shell-format", "editorconfig.editorconfig", "redhat.vscode-yaml", "ms-vscode-remote.remote-containers", "hashicorp.terraform", "redhat.vscode-xml", "redhat.vscode-xml", "redhat.vscode-yaml", "ms-vscode.PowerShell"]
linux = [
  "local.omarchy-theme",
  "catppuccin.catppuccin-vsc",
]
windows = [
  "ms-vscode.powershell",
]

# pkl-vscode
# https://github.com/apple/pkl-vscode
# Installed by VSIX
