[packages.linux]
  dnfs = ["git", "curl", "bash", "zsh", "bat", "zoxide", "unzip", "jq", "ncdu", "awscli", "code", "nodejs"]
  apts = ["git", "curl", "bash", "bat", "zoxide", "unzip", "jq", "ncdu", "direnv", "code", "nodejs"]
  flatpak = [
    "com.bitwarden.desktop",
    "com.synology.SynologyDrive",
    "md.obsidian.Obsidian",
    "org.videolan.VLC",
  ]
  pacman = [
    "bat",
    "bitwarden-cli",
    "bitwarden",
    "btop",
    "chezmoi",
    "chromium",
    "glow",
    "gum",
    "jq",
    "lazydocker",
    "meld",
    "mise-bin",
    "obsidian",
    "ripgrep",
    "starship",
    "steam",
    "syncthing",
    "visual-studio-code-bin",
  ]

[packages.windows]
  powershell = ["Posh-Git", "Terminal-Icons", "PsReadLine", "Get-WHOIS"]
  winget = [
    "JanDeDobbeleer.OhMyPosh",
    "Git.Git",
    "Microsoft.PowerShell",
    "Microsoft.VisualStudioCode",
    "twpayne.chezmoi",
    "Obsidian.Obsidian",
    "OpenWhisperSystems.Signal",
    "Greenshot.Greenshot",
    "Warrensbox.TerraformSwitcher",
    "OpenJS.NodeJS.LTS"
  ]
  scoop = [
    "Bitwarden.CLI",
    "Bitwarden.Bitwarden",
    "Mozilla.Firefox",
    "Discord.Discord",
    "Valve.Steam",
    "xpipe-io.xpipe",
    "GuinpinSoft.MakeMKV",
    "Plex.Plex",
    "Synology.SynologyDriveClient",
    "Tailscale.Tailscale",
    "TheDocumentFoundation.LibreOffice"
  ]
