[packages]
  mise = [
    "agy",
    "aqua:owenlamont/ryl",
    "betterleaks",
    "bitwarden-secrets-manager",
    "codex",
    "copilot",
    "crush",
    "editorconfig-checker",
    "gemini",
    "gh",
    "github:daptify14/chezit",
    "go:mvdan.cc/sh/v3/cmd/shfmt",
    "hk",
    "java",
    "lua",
    "node",
    "npm:@kitlangton/ghui",
    "opencode",
    "oxfmt",
    "oxlint",
    "pkl",
    "python",
    "rg",
    "ripgrep",
    "shellcheck",
    "shellharden",
    "tombi",
    "yazi",
  ]

[packages.linux]
  pacman = [
    "bat",
    "bitwarden-cli",
    "bitwarden",
    "btop",
    "chezmoi",
    "chromium",
    "glow",
    "gum",
    "jq",
    "lazydocker",
    "meld",
    "mise-bin",
    "obsidian",
    "ripgrep",
    "starship",
    "steam",
    "syncthing",
    "visual-studio-code-bin",
  ]

[packages.windows]
  psgallery = [
    "Catesta",
    "Cobalt",
    "ConsoleMonster",
    "EZOut",
    "FormatMarkdownTable",
    "HelpOut",
    "InvokeBuild",
    "JoinModule",
    "JT.WriteLog",
    "Microsoft.PowerShell.ThreadJob",
    "Microsoft.WinGet.Client",
    "Microsoft.WinGet.CommandNotFound",
    "Pester",
    "Plaster",
    "platyPS",
    "PSClassUtils",
    "PSDataKit",
    "PSDesiredStateConfiguration",
    "PSGraph",
    "PSScriptAnalyzer",
    "PSScriptTools",
    "PwshSpectreConsole",
    "SimplySql"
  ]
  winget = [
    "Microsoft.AdministrativeTemplates",
    "Microsoft.AppInstaller",
    "Microsoft.DotNet.DesktopRuntime.6",
    "Microsoft.DotNet.DesktopRuntime.7",
    "Microsoft.DotNet.DesktopRuntime.8.x64",
    "Microsoft.DotNet.Native.Runtime",
    "Microsoft.DotNet.Runtime.8",
    "Microsoft.DotNet.SDK.10",
    "Microsoft.DotNet.SDK.8",
    "Microsoft.DotNet.SDK.9",
    "Microsoft.UI.Xaml.2.8",
    "Microsoft.VCLibs.14",
    "Microsoft.VCLibs.Desktop.14",
    "Microsoft.VCRedist.2015+.x64",
    "Microsoft.VCRedist.2015+.x86",
    "Microsoft.WindowsAppRuntime.2",
    "Tailscale.Tailscale"
  ]
  scoop = [
    "extras/advancedrenamer",
    "extras/ariang-native",
    "extras/audacity",
    "extras/bitwarden",
    "extras/bruno",
    "extras/cc-switch",
    "extras/chromium",
    "extras/clever-ffmpeg",
    "extras/cpu-z",
    "extras/dbeaver",
    "extras/ditto",
    "extras/etcher",
    "extras/exifcleaner",
    "extras/exifglass",
    "extras/freecad",
    "extras/g-helper",
    "extras/git-credential-manager",
    "extras/gpu-z",
    "extras/gramps",
    "extras/hwinfo",
    "extras/iconview",
    "extras/irfanview",
    "extras/jqp",
    "extras/krokiet",
    "extras/mobaxterm",
    "extras/notepadplusplus",
    "extras/obsidian",
    "extras/onecommander",
    "extras/openscad",
    "extras/orcaslicer",
    "extras/picview",
    "extras/plantuml",
    "extras/prime95",
    "extras/raindrop.io",
    "extras/rufus",
    "extras/scoop-completion",
    "extras/scrawler",
    "extras/sfsu",
    "extras/shutup10",
    "extras/snaketail",
    "extras/speccy",
    "extras/station",
    "extras/sweethome3d",
    "extras/syncthingtray",
    "extras/sysinternals",
    "extras/terminal-icons",
    "extras/theia-ide",
    "extras/total-registry",
    "extras/unigetui",
    "extras/upscayl",
    "extras/vcredist2022",
    "extras/vidiot",
    "extras/vlc",
    "extras/windhawk",
    "extras/winmerge",
    "extras/wiztree",
    "extras/wtq",
    "extras/xc",
    "extras/xnviewmp",
    "extras/xpipe",
    "extras/youtube-dl-gui",
    "java/openjdk",
    "main/7zip",
    "main/7zip19.00-helper",
    "main/aria2",
    "main/ascii-image-converter",
    "main/bitwarden-cli",
    "main/cacert",
    "main/charm-gum",
    "main/cheat",
    "main/cmake",
    "main/codegraph",
    "main/czkawka",
    "main/dark",
    "main/dependency-check",
    "main/dprint",
    "main/exiftool",
    "main/ffmpeg",
    "main/fx",
    "main/fzf",
    "main/gh",
    "main/git-lfs",
    "main/git",
    "main/glow",
    "main/graphviz",
    "main/grex",
    "main/hyperfine",
    "main/innounp",
    "main/iperf3",
    "main/jc",
    "main/jq",
    "main/less",
    "main/lessmsi",
    "main/mask",
    "main/mdq",
    "main/nuget",
    "main/openapi-generator-cli",
    "main/opentofu",
    "main/pandoc",
    "main/pastel",
    "main/perl",
    "main/pester",
    "main/poppler",
    "main/ripgrep",
    "main/shfmt",
    "main/silicon",
    "main/sq",
    "main/sqlite",
    "main/starship",
    "main/sudo",
    "main/svtplay-dl",
    "main/syncthing",
    "main/tailspin",
    "main/tlrc",
    "main/ttyd",
    "main/uv",
    "main/vhs",
    "main/webhook",
    "main/wget",
    "main/youtube-dl",
    "main/yq",
    "main/zizmor",
    "main/zoxide",
    "nerd-fonts/Cascadia-Code",
    "nerd-fonts/CascadiaCode-NF-mono",
    "nerd-fonts/CascadiaCode-NF-Propo",
    "nerd-fonts/CascadiaCode-NF",
    "nirsoft/filetypesman",
    "nirsoft/lanipscanner",
    "nirsoft/netresview",
    "nirsoft/registrychangesview",
    "nirsoft/simplewmiview",
    "nirsoft/socketsniff",
    "nirsoft/WakeMeOnLan",
    "versions/googlechrome-dev",
    "versions/nodejs24",
    "versions/pwsh-beta",
    "versions/steam",
    "versions/vscode-insiders",
    "versions/windows-terminal-preview",
  ]
