[vscode]
  extensions = [
    "davidanson.vscode-markdownlint",
    "dracula-theme.theme-dracula",
    "editorconfig.editorconfig",
    "emilast.logfilehighlighter",
    "fanaticpythoner.better-todo-tree",
    "foxundermoon.shell-format",
    "hashicorp.terraform",
    "hverlin.mise-vscode",
    "ibm.output-colorizer",
    "mads-hartmann.bash-ide-vscode",
    "ms-azuretools.vscode-containers",
    "ms-sarifvscode.sarif-viewer",
    "ms-vscode-remote.remote-containers",
    "ms-vscode.vscode-chat-customizations-evaluations",
    "openai.chatgpt",
    "openai.codex-audio",
    "owenlamont.ryl",
    "pkl.pkl-vscode",
    "redhat.vscode-xml",
    "redhat.vscode-yaml",
    "sumneko.lua",
    "timonwong.shellcheck",
    "tombi-toml.tombi",
    "xembly.gomplate",
  ]
