[vscode]
extensions = [
  "davidanson.vscode-markdownlint",
  "dracula-theme.theme-dracula",
  "editorconfig.editorconfig",
  "emilast.logfilehighlighter",
  "enkia.tokyo-night",
  "foxundermoon.shell-format",
  "gruntfuggly.todo-tree",
  "hashicorp.terraform",
  "hverlin.mise-vscode",
  "ibm.output-colorizer",
  "local.omarchy-theme",
  "mads-hartmann.bash-ide-vscode",
  "mkhl.shfmt",
  "ms-azuretools.vscode-containers",
  "ms-vscode-remote.remote-containers",
  "ms-vscode.vscode-chat-customizations-evaluations",
  "openai.chatgpt",
  "openai.codex-audio",
  "pkl.pkl-vscode",
  "redhat.vscode-xml",
  "redhat.vscode-yaml",
  "sumneko.lua",
  "timonwong.shellcheck",
  "tombi-toml.tombi",
  "xembly.gomplate",
]
