[ya]
  plugins = [
    "yazi-rs/plugins:chmod",         # https://github.com/yazi-rs/plugins/tree/main/chmod.yazi
    "yazi-rs/plugins:diff",          # https://github.com/yazi-rs/plugins/tree/main/diff.yazi
    "yazi-rs/plugins:mime-ext",      # https://github.com/yazi-rs/plugins/tree/main/mime-ext.yazi
    "yazi-rs/plugins:smart-enter",   # https://github.com/yazi-rs/plugins/tree/main/smart-enter.yazi
    "yazi-rs/plugins:full-border",   # https://github.com/yazi-rs/plugins/tree/main/full-border.yazi
    "yazi-rs/plugins:smart-filter",  # https://github.com/yazi-rs/plugins/tree/main/smart-filter.yazi
    "yazi-rs/plugins:smart-paste",   # https://github.com/yazi-rs/plugins/tree/main/smart-paste.yazi

    # "yazi-rs/plugins:diff",         # https://github.com/yazi-rs/plugins/tree/main/diff.yazi
    # "yazi-rs/plugins:diff",         # https://github.com/yazi-rs/plugins/tree/main/diff.yazi
  ]
  flavors = [
    "yazi-rs/flavors:dracula",       # https://github.com/yazi-rs/flavors/tree/main/dracula.yazi
  ]
