#:schema https://yazi-rs.github.io/schemas/theme.json
{{/* chezmoi:modify-template */}}

{{/* Load default configuration */ -}}
{{ $default_file := (joinPath .chezmoi.homeDir ".config/yazi/theme-dark.toml") }}
{{ $default := (include $default_file) | fromToml -}}

{{/* Load existing configuration */ -}}
{{ $existing := dict -}}
{{ if not (.chezmoi.stdin | trim | empty) -}}
{{   $existing = fromToml .chezmoi.stdin -}}
{{ end -}}

{{/* Merge existing with default, giving precedence to existing */ -}}
{{ $result := merge $existing $default -}}

{{/* Set dracula theme */ -}}
{{ $result := setValueAtPath "flavor.dark" "dracula" $result -}}

{{ toToml $result -}}

# TODO: https://yazi-rs.github.io/docs/configuration/theme/#icon
# TODO: yazi use https://github.com/nvim-tree/nvim-web-devicons
# TODO: Add more [[icon.dirs]]
# TODO: Add more [[icon.files]]
# TODO: Add more [[icon.exts]]
