#:schema https://yazi-rs.github.io/schemas/yazi.json
{{/* chezmoi:modify-template */}}

{{/* Load default configuration */ -}}
{{ $default_file := (joinPath .chezmoi.homeDir ".config/yazi/yazi-default.toml") }}
{{ $default := (include $default_file) | fromToml -}}

{{/* Load existing configuration */ -}}
{{ $existing := dict -}}
{{ if not (.chezmoi.stdin | trim | empty) -}}
{{   $existing = fromToml .chezmoi.stdin -}}
{{ end -}}

{{/* Merge existing with default, giving precedence to existing */ -}}
{{ $result := merge $existing $default -}}

{{ toToml $result -}}
