#:schema https://yazi-rs.github.io/schemas/theme.json

{{/* chezmoi:modify-template */ -}}

#{ {/* Load existing configuration */ -}}
#{ { $config := toToml dict -}}
#{ { if not (.chezmoi.stdin | empty) -}}
#{ {   $config = .chezmoi.stdin -}}
#{ { end -}}

{{/* Load defult keymap */ -}}
{{ $default := include (joinPath .chezmoi.homeDir ".config/yazi/theme-dark.toml") | fromToml -}}

{{/* Set dracula theme */ -}}
{{ $output := setValueAtPath "flavor.dark" "dracula" $default -}}

{{ toToml $default }}
