#:schema https://mise.jdx.dev/schema/mise.json

[task_config]
includes = ["tasks.toml"]

[env]
_.path = "~/bin"

[settings]
upgrade.auto_prune = false
experimental = true
color_theme = "catppuccin"

[settings.skills]
dir = ".agents/skills"
auto_sync = true
prune = true

[settings.packslip]
exec = true

[settings.github]
credential_command = "gh auth token"
use_git_credentials = true

[tools]
"github:daptify14/chezit" = { version = "latest", os = ["linux"] }
"npm:@kitlangton/ghui" = "latest"
"packslip:github.com/jdx/hk" = "latest"
codex = "latest"
copilot = "latest"
gemini = { version = "latest", allow_builds = ["@github/keytar", "node-pty"] }
gh = "latest"
node = "26.7.0"
opencode = "latest"
yazi = "latest"
tombi = "1.5.5"
go = "latest"
agy = "latest"
betterleaks = "latest"
crush = "latest"
java = "latest"
"aqua:owenlamont/ryl" = "latest"
ripgrep = "latest"
lua = "latest"
