#:schema https://www.schemastore.org/tombi.json

toml-version = "v1.1.0"

[files]
  include = ["**/*.toml"]
  exclude = ["**/modify_*.toml"]

[format]
[format.rules]
  indent-table-key-value-pairs = true
  key-quote-style = "double"
  line-width = 120
  trailing-comment-alignment = true

  # [lint]
  # [lint.rules]
